### ISSUE TITLE
sqlite封装的使用

### ISSUE THREAD

**Issue by lmdiloveu** [lyloou/lou#1]
// 初始化
        LouSQLite.init(this.getApplicationContext(), new MyCallBack());
初始化是不是应该放在Application，而不是Activity？难道每一个Activity都要初始化一次？

**Comment by lyloou** [comment]
嗯，是的，最好是放在 Application 中。
我在项目中也是放在 Application 中的。
我在写这个demo时，只有一个界面用到，就放在一起写了，不好意思没有解释清楚
